ontologies:
  source:
    - url: 'https://spec.industrialontologies.org/ontology/AboutIOFDev/'
    - url: 'https://spec.industrialontologies.org/ontology/MetadataIOF/'
  catalog_path:
    - ontologies/catalog-v001.xml
  module_ignore_pattern:
    - '^(About|Metadata|Load).*'
    - 'http.*(About|Metadata).*'
  module_class_iri: 'http://www.omg.org/techprocess/ab/SpecificationMetadata/Module'
  maturity_level_definition:
    - iri: 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/Released'
      label: 'Release'
    - iri: 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/Provisional'
      label: 'Provisional'
maturity_level_property: 'https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/maturity'